### ISSUE TITLE
Ensure the "Choose File" button appears for users on mobile devices.

### ISSUE THREAD

**Issue by Keyairra-S-Wright** [abbybenvenutti/iendorsebooker#11]
The choose photo button (where users upload their avatar image) does not appear on mobile devices simulated through the browser.

![image](https://user-images.githubusercontent.com/38898288/83191319-d04d7d80-a101-11ea-9d19-6ad4a6610792.png)

On an Android phone with light mode, the choose file button does appear. Though, we should ensure that the button is present across other simulated and actual mobile devices.

**Comment by epark17** [comment]
both locally and on the deployed site?

**Comment by Keyairra-S-Wright** [comment]
seems like this issue is locally on dark mode. I am not sure if it also occurs on mobile devices in dark mode. my device uses light mode.

**Comment by Keyairra-S-Wright** [comment]
No longer seeing this issue.
