### ISSUE TITLE
Create a uniformed flow of text and image alignment within the header

### ISSUE THREAD

**Issue by Keyairra-S-Wright** [abbybenvenutti/iendorsebooker#12]
The elements with the endorsement title and user directions are aligned to the left. The Campaign logo is aligned center. There could be enhanced visual appeal if those items have uniform alignment.

<img width="1386" alt="Screen Shot 2020-05-28 at 4 50 33 PM" src="https://user-images.githubusercontent.com/38898288/83193067-7306fb80-a104-11ea-884e-3cdcaca4d424.png">

**Comment by epark17** [comment]
I merged the PR with the header alignments - let me know if you see the changes after a pull :)

**Comment by Keyairra-S-Wright** [comment]
Thanks for making the changes, @epark17 .
